<a href="https://colab.research.google.com/github/allnlk/NM/blob/main/%D0%9B%D0%A0_4_%D0%A4%D0%86%D0%A2_2_10_%D0%9A%D1%83%D0%B1%D1%80%D0%B0%D0%BA_%D0%90_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ЛР 4. ФІТ 2-10. Кубрак А. Варіант 15 (присутня на парі)

In [2]:
import numpy as np
np.__version__

'2.0.2'

In [3]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[1, 4, 3],
       [4, 1, 4],
       [4, 3, 3]])

In [4]:
det = np.linalg.det(matrix)
det

np.float64(31.0)

In [5]:
product = np.prod(matrix)
product

np.int64(6912)

In [6]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(6912)

In [7]:
sum_1 = np.sum(matrix)
sum_1

np.int64(27)

In [8]:
np.max(matrix)

np.int64(4)

In [9]:
np.min(matrix)

np.int64(1)

In [12]:
np.mean(matrix)

np.float64(3.0)

In [11]:
max_element = np.max(matrix)

print("Найбільший елемент матриці: ", max_element)

min_element = np.min(matrix)

print("Найменший елемент матриці: ", min_element)

Найбільший елемент матриці:  4
Найменший елемент матриці:  1


In [13]:
np.sqrt(matrix)

array([[1.        , 2.        , 1.73205081],
       [2.        , 1.        , 2.        ],
       [2.        , 1.73205081, 1.73205081]])

In [14]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка: ")
print(row_sums)

Сума елементів кожного рядка: 
[[ 8]
 [ 9]
 [10]]


In [15]:
vector = np.random.randint(0, 10, size = 25)
vector

array([6, 8, 7, 8, 8, 2, 0, 7, 4, 4, 3, 9, 2, 8, 3, 4, 6, 5, 1, 9, 6, 0,
       4, 9, 1])

In [16]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 8, 8, 8, 8, 7, 7, 6, 6, 6, 5, 4, 4, 4, 4, 3, 3, 2, 2, 1,
       1, 0, 0])

In [22]:
a = np.array([[1, -2, 1], [2, -1, 1], [3, 2, 2]])
b = np.array([4, 3, 2])

x = np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [ 0. -1.  2.]
Матричний метод [-0. -1.  2.]


In [23]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(0.0), np.float64(-1.0), np.float64(2.0)]
